fallback to 7.11
the worker key needs to be updated. It's in an old format that's no
longer supported by us. Was getting this error in the logs:

error: invalid argument for flag `--tsa-worker-private-key' (expected *flag.PrivateKey): x509: failed to parse private key (use ParsePKCS1PrivateKey instead for this key format)

Signed-off-by: Taylor Silva <dev@taydev.net>